### ISSUE TITLE
Web Link via push notification is launching safari 

### ISSUE THREAD

**Issue by mcg95** [comapi/comapi-sdk-ios-objc#18]
We have a Firebase Dynamic Link we are sending in the dd_deeplink property of the push notification. From what I observed while debugging, in the CMPComapiClient file, the `- (void)handleNotificationResponse:(UNNotificationResponse *)notificationResponse completion:(void (^)(BOOL, NSDictionary * _Nonnull))completion ` function is calling `UIApplication.sharedApplication openURL` function once the canOpenURL check is done. 

When it comes to sending deeplinks using the URLScheme such as `myapp://`, it will work as expected. But when web links are sent, due to them containing https, it opens them in Safari. Ideally this web link needs to be sent back via the completion without launching safari. 

This would allow more flexibility as the application using the SDK can decide on how to control the behaviour of receiving a web url. In our case we want to retrieve the Firebase Dynamic Link and resolve it via the Firebase library to get the underlying data. But as of now, we seem to be navigated to safari as soon as the application opens.

```objective-c
        if ([UIApplication.sharedApplication canOpenURL:link]) {
            [UIApplication.sharedApplication openURL:link options:@{} completionHandler:^(BOOL success) {
                if (!success) {
                    logWithLevel(CMPLogLevelError, [NSString stringWithFormat:@"Couldn't open URL - %@", link], nil);
                }
                if (completion) {
                    completion(YES, userInfo);
                }
                return;
            }];
        }
``` 

Suggested fix
```objective-c
        if ([UIApplication.sharedApplication canOpenURL:link]) {
            if ([link.absoluteString hasPrefix:@"http://"] || [link.absoluteString hasPrefix:@"https://"]) {
                // If the link contains "http" or "https", call completion directly
                if (completion) {
                    completion(YES, userInfo);
                    return;
                }
            }
            
            [UIApplication.sharedApplication openURL:link options:@{} completionHandler:^(BOOL success) {
                if (!success) {
                    logWithLevel(CMPLogLevelError, [NSString stringWithFormat:@"Couldn't open URL - %@", link], nil);
                }
                if (completion) {
                    completion(YES, userInfo);
                }
                return;
            }];
        }
```

**Comment by DaveBaddeley** [comment]
Hi,

So the SDKs behavior is by design when using the deep link options. If you want to pass data to the app via the push message and choose how to process it in the app we recommend using the custom body option when sending the push message and putting the data you want to pass in the FCM _data_ field and the APNS _payload_ field. Usually this takes the form of a JSON string, but can be any data. You can find details on sending custom body push messages here: [https://developer.dotdigital.com/reference/channel-push#custom-body](https://developer.dotdigital.com/reference/channel-push#custom-body)

When the SDK receives the custom body it will simply make the data available to the app for interpretation; alternatively you could create a deep link scheme for your app and pass the original URL via that URL encoded.

We hope these suggestions help.
